version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: multisport-dev-db
    environment:
      POSTGRES_DB: multisport
      POSTGRES_USER: multisport_user
      POSTGRES_PASSWORD: multisport_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: 